
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_fundamentals'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_fundamentals'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  start_date_var: "'2020-01-01'"
  end_date_var: "'2022-12-31'"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_fundamentals:
      +required_tests: {"unique.*|not_null": 1}
      # Applies to all files under models/example/
      staging:
          +materialized: view
          +tags: "staged_views"
          +persist_docs:
             relation: true
             columns: true
          tpch:
            +schema: tpch
            +tags: "snowflake sample tpch views"
      marts:
          +required_tests: {"relationship.*": 1}
          core:   
              +materialized: table  

seeds:
  dbt_fundamentals:
      +database: raw
    
      country_codes:
        +alias: country_mappings
      currencies:
        +meta:
           default_currency: USD

tests:
  dbt_fundamentals:
      +schema: dbt_audit

    
